# run 10 instances for 500K_condor_signal.sh

#executable = /gfsvol01/atlas/giuliac/HiggsTutorial/MG5_aMC_v3_5_6/Delphes/EJ_reproduction/tasks/20250428_Task17/500K_condor_signal.sh
executable = 500K_condor_signal.sh
arguments = $(Item)

#initialdir              = /gfsvol01/atlas/giuliac/HiggsTutorial/MG5_aMC_v3_5_6/Delphes
#initialdir              = /gfsvol01/atlas/giuliac
#transfer_input_files    = condor/20250428_Task17/pythia8_cards/signal_$(Item).cmnd, HiggsTutorial/MG5_aMC_v3_5_6/Delphes/EJ_reproduction/delphes_cards/delphes_card_ATLAS_EJ_reproduction_Reclustering.tcl 

getenv=True

request_cpus=1
request_memory=2048
request_disk=10000000

#log = /gfsvol01/atlas/giuliac/condor/20250428_Task17/condor_out/signal_job_$(Item).out
#output = /gfsvol01/atlas/giuliac/condor/20250428_Task17/condor_out/signal_job_$(Item).out
#error = /gfsvol01/atlas/giuliac/condor/20250428_Task17/condor_out/signal_job_$(Item).out
log = signal_job_$(Item).out
output = signal_job_$(Item).out
error = signal_job_$(Item).out

notification = complete
notify_user = giulia.cossutti@cern.ch

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue from seq 1 10 |
